version: 2

on:
  push:
    paths:
    - 'datamesh-ddl/**'
    branches:    
      - main
jobs:
  build:
    filters:
      branches:
        ignore:
          - /.*-pull-request-.*/
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - *build
      - run:
          name: Install gcloud CLI
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project $GCLOUD_PROJECT_ID
      - run:
          name: List Changed Files
          command: |
            CHANGED_FILES=$(git diff --name-only $CIRCLE_BRANCH $REFERENCE_BRANCH)
            echo "Changed files:"
            echo "$CHANGED_FILES"
      - run:
          name: List Changed Files2
          command: |
            CHANGED_FILES=$(git diff --name-only --diff-filter=d $CIRCLE_BRANCH $REFERENCE_BRANCH datamesh-ddl/)
            echo "Changed files:"
            echo "$CHANGED_FILES"
      - run:
          name: Execute DDL in BigQuery
          command: |
            for FILE in $CHANGED_FILES; do
              bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=$GCLOUD_PROJECT_ID < $FILE
            done
      - run:
          name: Execute All DDL in BigQuery
          command: |
            bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=$GCLOUD_PROJECT_ID < $FILE
            echo "executed ddl files"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build