version: 2
jobs:
 check-changes-in-repo:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
         name: List Changed Files
         command: |
          git diff --name-only HEAD^..HEAD | grep -E '.*\.sql' | sort > changed_files.txt
          echo "`cat changed_files.txt`"
          export CHANGED_FILES=`git diff --name-only HEAD^..HEAD | grep -E '.*\.sql'`
          echo $CHANGED_FILES
 
 set-bigquery-connection:
    docker:
      - image: google/cloud-sdk
    steps:
     - checkout
     - run:
          name: Install gcloud CLI
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project $GCLOUD_PROJECT_ID
         
 run-changes-in-repo:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
         name: Run Changed Files
         command: |
          for file in ("`cat changed_files.txt`"`);do
           echo "`cat file`"
           bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=$GCLOUD_PROJECT_ID < \$file
          done

workflows:
  version: 2
  build-deploy:
    jobs:
      - check-changes-in-repo:
          filters:
           branches:
            only: main
      - set-bigquery-connection:
          filters:
           branches:
            only: main
      - run-changes-in-repo:
          requires:
            - set-bigquery-connection
          filters:
           branches:
            only: main