version: 2
jobs:
 check-changes-in-repo:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
         name: List Changed Files
         command: |
          git diff --name-only HEAD^..HEAD > changed_files.txt
          echo "`cat changed_files.txt`"


workflows:
  version: 2
  build-deploy:
    jobs:
      - check-changes-in-repo:
          filters:
           branches:
            only: main